---
- hosts: tomcatservers
  sudo: yes

  vars:
    app_version: release-0.03


  tasks:
  - name: Install EPEL repo
    yum: name=epel-release state=present


  - name: Restart Apache
    service: name=httpd state=restarted
  - name: Remove old files foo
    file: path=/var/www/html/index.html state=absent

  - name: deploy website content
    git: repo=https://github.com/rsthakur83/release.git
         dest=/var/www/html
         version={{ app_version }}
         force=yes
