---
- hosts: tomcatservers
  sudo: yes

  environment:
    http_proxy: http://10.103.30.18:8080
    https_proxy: http://10.103.30.18:8080

  tasks:
  - name: Install EPEL repo
    yum: name=epel-release state=present

#  - name: Install tomcat
#    yum: name=tomcat state=present

  - name: Restart Apache
    service: name=httpd state=restarted
  - name: Remove old files foo
    file: path=/var/www/html/index.html state=absent


  - name: Clone git repository
    git: >
      repo=https://github.com/rsthakur83/Tutorial.git
      dest=/var/www/html
      force=yes
      recursive=no

#  - name: Remove old files foo
#    file: path=/var/www/html/index.html state=absent
#  - name: copy file from machine1 to local
#    fetch: src=https://github.com/rsthakur83/Tutorial/index.html dest=/tmp/app
#  - name: copy file from machine1 to local
#    copy: src=/tmp/app/index.html dest=/var/www/html/index.html
#  - copy:
#     src: /tmp/app/index.html
#     dest: /var/www/html/index.html
#     owner: root
#     group: root
#     mode: 0644
